# SRC: https://github.com/numtide/treefmt
# REF: https://treefmt.com/latest/getting-started/configure/#config-file

walk = "git"
excludes = [
	"*.conf",
	"*.key",
	"*.lock",
	"*.ogg",
	"*.patch",
	"License",
	"home/file/jetbrains/ideavimrc",
	"home/file/ssh/config",
]

[formatter.nixfmt-rfc-style]
command  = "nixfmt"
options  = [ "-s" ]
includes = [ "*.nix" ]

[formatter.shfmt]
command  = "shfmt"
options  = [ "-s", "-w" ]
includes = [ "*.sh" ]

[formatter.prettier]
command  = "prettier"
options  = [ "-w" ]
includes = [ "*.css" ]

[formatter.stylua]
command  = "stylua"
includes = [ "*.lua" ]
